image: Visual Studio 2017
build_script:
  - ps: |
      if ($env:enable_rdp -eq "true") {
          $blockRdp = $true;
          iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
      }
  - gradlew.bat assembledebug
